# Generated by Django 3.2.9 on 2021-11-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_mate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='problems',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
