# Generated by Django 3.2.9 on 2021-11-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_mate', '0003_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='tittle',
            new_name='title',
        ),
    ]
