# Generated by Django 3.2.9 on 2021-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio_mate', '0004_rename_tittle_subject_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('solution_file', models.FileField(upload_to='')),
            ],
        ),
    ]
